name: lithabit
description: A library books app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  barcode: ^2.2.4
  barcode_widget: ^2.0.4
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdfviewer: ^22.1.34
  http: ^1.0.0
  cached_video_player: ^2.0.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build: ^2.4.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/harry_potter.pdf
    - assets/Aadujeevitham -by Benyamin.pdf
    - assets/loader.gif
    - assets/Never_lie_against_truth.pdf
    - assets/khasakkinte-ithihasam.pdf
 